### PR TITLE
visitor can create an account

### PR DESCRIPTION
**Pull request by jtruong2**
story 9 is done. please review

### CODE REVIEW

**Comment by wratterman** [comment]
Well done! Besides some refactoring this looks great!

**Comment by bretfunk** [comment]
Should we take out the comments in the spec files?

**Comment by bretfunk** [comment]
@wratterman What refactoring do you suggest?  Creating a login method?

**Comment by wratterman** [comment]
@bretfunk on cleanup we will probably want to but for now we are pretty good. 🔴  👉  💚  👉  Refactor.

**Pull request merged**
